name: Build + publish PDF

on:
  push:
    tags:
      - "v*"

jobs:
  build-publish-pdf:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build pdf
      run: make hackpack

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: hackpack.pdf
